# Generated by Django 2.1.5 on 2019-02-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbs.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bbs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
